; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32H750VB]
platform = ststm32
board = genericSTM32H750VB
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink 
build_flags = 
   -DUSE_HAL_DRIVER 
   -mfloat-abi=hard   
   -mfpu=fpv4-sp-d16
   -mcpu=cortex-m7
   -DSTM32H750xx
   -mthumb
   -Ilib/FreeRTOS/include
   -Ilib/FreeRTOS/portable/GCC/ARM_CM7
   -Ilib/FreeRTOS/portable/MemMang

extra_scripts = force_fpu_flags.py
